import type { Config } from 'tailwindcss'

// Ported 1:1 from the old per-page inline `tailwind.config` (Tailwind CDN)
// script tag so every existing className in the site keeps working exactly
// as before. Kept as static values (not shadcn's CSS-variable convention)
// since the site already has its own Material3-style token names
// (primary, on-primary, surface, ...) — introducing shadcn's semantic
// background/foreground/primary CSS vars here would collide with them.
export default {
  darkMode: ['class'],
  content: ['./index.html', './menu.html', './hakkimizda.html', './rezervasyon.html', './iletisim.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#1c1b1b',
        'secondary-container': '#df2842',
        'surface-container-highest': '#e3e2e2',
        'surface-variant': '#e3e2e2',
        'on-secondary-fixed': '#400009',
        'on-primary-container': '#858383',
        'on-secondary': '#ffffff',
        'on-surface': '#1b1c1c',
        'outline-variant': '#c4c7c7',
        'surface-dim': '#dbdad9',
        'surface-container-high': '#e9e8e8',
        'error-container': '#ffdad6',
        'surface-container-low': '#f4f3f3',
        'surface-container': '#efeded',
        'secondary-fixed': '#ffdad9',
        'secondary-fixed-dim': '#ffb3b3',
        'on-tertiary-fixed-variant': '#454747',
        'inverse-on-surface': '#f2f0f0',
        'primary-fixed': '#e5e2e1',
        primary: '#000000',
        secondary: '#ba002c',
        'on-background': '#1b1c1c',
        'primary-fixed-dim': '#c8c6c5',
        'tertiary-fixed': '#e2e2e2',
        'on-primary-fixed-variant': '#474746',
        'on-primary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#920021',
        'inverse-primary': '#c8c6c5',
        'on-error-container': '#93000a',
        background: '#faf9f9',
        'on-surface-variant': '#444748',
        surface: '#faf9f9',
        'on-tertiary-container': '#838484',
        'inverse-surface': '#2f3031',
        'surface-tint': '#5f5e5e',
        'on-secondary-container': '#fffbff',
        'surface-bright': '#faf9f9',
        'on-error': '#ffffff',
        'tertiary-container': '#1a1c1c',
        error: '#ba1a1a',
        tertiary: '#000000',
        outline: '#747878',
        'on-tertiary-fixed': '#1a1c1c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1200px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        unit: '8px',
      },
      fontFamily: {
        'display-lg': ['EB Garamond'],
        'headline-lg': ['EB Garamond'],
        'body-md': ['Manrope'],
        'body-lg': ['Manrope'],
        'headline-md': ['EB Garamond'],
        'label-sm': ['Manrope'],
        'headline-lg-mobile': ['EB Garamond'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config
